# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-23 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
